version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Dependencies
          command: npm ci
      - run:
          name: Tests
          command: npm run test
