version: 2

jobs:
  build:
    working_directory: ~/vitaminjs
    docker:
      - image: circleci/node:7.7
    steps:
      - checkout
      - run:
          name: Dependencies
          command: npm install
      - run:
          name: Tests
          command: npm run test
